services:
  backend:
    
    environment:
        - WDS_SOCKET_HOST=127.0.0.1 
        - CHOKIDAR_USEPOLLING=true
        - WATCHPACK_POLLING=true 
    build: ./backend    
    ports:
      - 5000:5000
  db:
    image: mongo
    ports:
      - 21017:21017